#!/usr/bin/env zsh
#
# zsh-prompt-simple
#
# https://github.com/atanvarno69/zsh-prompt-simple
#
# MIT License <https://opensource.org/licenses/MIT>

prompt_simple_help () {
    cat <<'EOF'
A simple prompt displaying the present working directory. This prompt is
colorable. You can invoke it with:

    prompt simple [OPTIONS...]

OPTIONS
    Mandatory arguments to long options are mandatory for short options too.

    -c | --color <COLOR>  Color to use for the prompt, defaults to green.
    -e | --error <COLOR>  Color to use when the last command exited with a
                          failure code, defaults to red.
    -s | --simpler        Display only the present working directory base name,
                          without the leading full path.
    -t | --time           Display the clock on the right of the screen.

COLOR
     For valid color options see:
     https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting
EOF
}

prompt_simple_setup () {
    # Set zsh options
    prompt_opts=(cr percent subst)

    # Set function option defaults
    color='green'; error='red'; simpler=0; time=0

    # Process function options
    while [ -n "${1}" ]; do
        case "${1}" in
            -c|--color) shift; color="${1}";;
            -e|--error) shift; error="${1}";;
            -s|--simpler) simpler=1;;
            -t|--time) time=1;;
            --) break;;
            -*) echo "Unrecognized option ${1}." 1>&2; return 2;;
            *) break;;
        esac
        shift
    done

    # Prepare PWD
    dir=$(print -P %~)
    lead=$(dirname ${dir})
    trail=$(basename ${dir})
    if [ "${lead}" = '.' ]; then
        lead=''
    elif [ "${lead}" = '/' ] && [ "${trail}" = '/' ]; then
        lead=''
    elif [ "${lead}" != '/' ]; then
        lead+='/'
    fi

    # PS1
    PS1=' %(?.%F{$color}.$F{$error})'
    [ "${simpler}" -eq 0 ] && PS1+='$lead'
    PS1+='%B$trail%b%f '

    # RPS1 and RPS2
    RPS1='%(?..%F{$error}[%?]%f)'
    RPS2=''
    [ "${time}" -gt 0 ] && { RPS1+='[%*]'; RPS2+='[%*]'; }

    # PS2, PS3, PS4 and SPROMPT
    PS2=' %F{$color}%_>%f '
    PS3=' %F{$color}?%f '
    PS4='+%F{$color}%N%f:%F{$color}%i>%f '
    SPROMPT='%F{red}%R%f > %F{$color}%r%f [nyae]%F{$color}?%f '
}

prompt_simple_setup "${@}"
